### ISSUE TITLE
serialport is not defined

### ISSUE THREAD

**Issue by mortezakarimi** [omcaree/node-mavlink#6]
when i use below code i get error serialport is not defined

``` JS
var mavlink = require('mavlink');
var myMAV = new mavlink(1,1,"v1.0",["common", "pixhawk"]);

myMAV.on("ready", function() {
    //parse incoming serial data
    serialport.on('data', function(data) {
        myMAV.parse(data);
    });

    //listen for messages
    myMAV.on("message", function(message) {
        console.log(message);
    });
});
```

**Comment by kpihus** [comment]
You need to install and initiate serialport module according to your serial parameters:

`
var mavlink = require('mavlink');
var SerialPort = require('serialport');
var serialport = new SerialPort('/dev/ttyUSB5', {
  baudRate: 57600
});

var myMAV = new mavlink(0,0)

myMAV.on("ready", function() {
  //parse incoming serial data
  serialport.on('data', function(data) {
    myMAV.parse(data);
  });

  //listen for messages
  myMAV.on("message", function(message) {
    console.log(message);
  });
});
`
